name = "icebox"
uuid = "e6055595-da08-4564-b1ed-fc7e0a967f69"
authors = ["Rose-max111"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
